{% set name = "azure-kusto-data" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-kusto-data-{{ version }}.tar.gz
  sha256: 230865e83d0063dbafb0c1a3d86699dd607c4f600f53c704993a56a44d91345d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - azure-identity >=1.3.1
    - msal>=1.6.0
    - python-dateutil >=2.8.0
    - requests >=2.13.0

test:
  imports:
    - azure.kusto
    - azure.kusto.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-kusto-python
  summary: Kusto Data Client
  description: |
    Kusto Python Client Library provides the capability to query Kusto clusters
    using Python. It is Python 3.x compatible and supports all data types
    through familiar Python DB API interface.
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/Azure/azure-kusto-python
  dev_url: https://github.com/Azure/azure-kusto-python

extra:
  recipe-maintainers:
    - xylar
