{% set name = "azure-kusto-data" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-kusto-data-{{ version }}.tar.gz
  sha256: 0ec48b6715abc85e82e4f30aa08b9d7e78a190a4d4572ed7794f7a3dca5847a7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - azure-identity >=1.5.0,<1.7.0
    - msal >=1.9.0,<2
    - python-dateutil >=2.8.0
    - requests >=2.13.0

test:
  imports:
    - azure.kusto
    - azure.kusto.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-kusto-python
  summary: Kusto Data Client
  description: |
    Kusto Python Client Library provides the capability to query Kusto clusters
    using Python. It is Python 3.x compatible and supports all data types
    through familiar Python DB API interface.
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/Azure/azure-kusto-python
  dev_url: https://github.com/Azure/azure-kusto-python

extra:
  recipe-maintainers:
    - xylar
